=== valtimo-platform/valtimo/backend/apps/dev/src/main/resources/config/case/woninginspectie/1-0-4/document/definition/woninginspectie.schema.document-definition.json
{
    "$id": "woninginspectie.schema",
    "type": "object",
    "title": "Woninginspectie",
    "$schema": "http://json-schema.org/draft-07/schema#",
    "required": [
        "aanvrager",
        "status"
    ],
    "properties": {
        "aanvrager": {
            "type": "object",
            "required": [
                "naam"
            ],
            "properties": {
                "naam": {
                    "type": "string"
                }
            }
        },
        "adres": {
            "type": ["string", "null"]
        },
        "status": {
            "type": "string"
        },
        "aantalKamers": {
            "type": ["integer", "null"]
        },
        "opmerking": {
            "type": ["string", "null"]
        },
        "migratedFrom": {
            "type": "string"
        },
        "inspectieAangevraagd": {
            "type": "boolean"
        },
        "inspectieStatus": {
            "type": "string"
        }
    }
}

=== valtimo-platform/valtimo/backend/apps/dev/src/main/resources/data/woninginspectie/1-0-1/documents/de-boer-full.json
{
    "aanvrager": {
        "naam": "Sophie de Boer"
    },
    "adres": "Lange Voorhout 12, 2514 ED Den Haag",
    "status": "in_behandeling",
    "aantalKamers": 4,
    "opmerking": "Inspectie aangevraagd",
    "migratedFrom": "1.0.0",
    "inspectieAangevraagd": true,
    "inspectieStatus": "gepland"
}
