=== valtimo-platform/valtimo/backend/apps/dev/src/main/resources/config/case/verhuizing/1-0-7/document/definition/verhuizing.schema.document-definition.json
{
    "$id": "verhuizing.schema",
    "type": "object",
    "title": "Verhuizing",
    "$schema": "http://json-schema.org/draft-07/schema#",
    "required": [
        "aanvrager",
        "status"
    ],
    "properties": {
        "aanvrager": {
            "type": "object",
            "required": [
                "naam"
            ],
            "properties": {
                "naam": {
                    "type": "string"
                },
                "emailadres": {
                    "type": ["string", "null"]
                },
                "email": {
                    "type": "string"
                }
            }
        },
        "nieuwAdres": {
            "type": ["string", "null"]
        },
        "status": {
            "type": "string"
        },
        "spoed": {
            "type": ["boolean", "null"]
        },
        "aantalPersonen": {
            "type": ["integer", "null"]
        },
        "oppervlakte": {
            "type": "number"
        },
        "verhuisdatum": {
            "type": "string",
            "format": "date"
        },
        "documenten": {
            "type": "array",
            "items": {
                "type": "string"
            }
        },
        "migratedFrom": {
            "type": "string"
        },
        "afgerond": {
            "type": "boolean"
        },
        "inspectieStatus": {
            "type": "string"
        },
        "inspectieAkkoord": {
            "type": "boolean"
        },
        "aantalKamers": {
            "type": "integer"
        },
        "geschatteWaarde": {
            "type": "number"
        }
    }
}

=== valtimo-platform/valtimo/backend/apps/dev/src/main/resources/data/verhuizing/1-0-2/documents/kok-mixed.json
{
    "aanvrager": {
        "naam": "Daan Kok",
        "email": "daan.kok@example.com"
    },
    "nieuwAdres": "Markt 1, 6211 CH Maastricht",
    "status": "in_behandeling",
    "spoed": null,
    "aantalPersonen": 6,
    "oppervlakte": 140.25,
    "afgerond": false,
    "aantalKamers": 5,
    "geschatteWaarde": 410000.0
}
